### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by volter9** [aintframework/aint_framework#3]
Hey there, just wonder, is this framework is still alive? Or already abandoned?

**Comment by lcf** [comment]
@Volter9 it's not being actively developed and supported, mostly left for "educational" purposes.

**Comment by volter9** [comment]
Oh, ok that's cool. I wonder is it suitable for production?

**Comment by lcf** [comment]
I don't see why not. I had a couple of apps running on it with no issue. You can try and see for yourself.

**Comment by volter9** [comment]
Thanks! :)
I really like the idea behind procedural/functional frameworks in PHP. They're small, fast, and easy to use. I even created my own implementation of procedural/functional framework. Unfortunately, there's only few procedural/functional frameworks in PHP that I know, your and mine.

Well, thank you for answering my questions, I'll try it out. :)
